[project]
name = "ntfsfind"
dynamic = ["version"]
description = "A command-line tool for searching files, directories, and alternate data streams directly from NTFS image files."
readme = "README.md"
license = "MIT"
authors = [
    { name = "sumeshi", email = "sum3sh1@protonmail.com" }
]
requires-python = ">=3.13"

dependencies = [
    "ntfsdump==3.1.0",
    "mft==0.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/ntfsfind/__about__.py"

[project.urls]
Homepage = "https://github.com/sumeshi/ntfsfind"
Repository = "https://github.com/sumeshi/ntfsfind"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "flake8>=7.3.0",
    "mypy>=2.1.0",
    "nuitka>=4.1.2",
    "pytest>=9.0.3",
    "zstandard>=0.25.0",
]

[project.scripts]
ntfsfind = 'ntfsfind.cli:main'
