name: build-binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: replace version
        run: |
          from pathlib import Path
          version = [l for l in Path('pyproject.toml').read_text().splitlines() if 'version' in l][0].split(' ')[-1].strip('\"')
          f = Path('src/ntfsfind.py')
          text = f.read_text().replace("version('ntfsfind')", f"\'{version}\'")
          f.write_text(text)
        shell: python

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: run python
        run: |
          poetry run ntfsfind -h

      - name: build
        run: |
          pip install pyinstaller
          pyinstaller --onefile -p . -p src -p ./.venv/Lib/ -p ./.venv/Lib/site-packages -n ntfsfind ./.venv/Scripts/ntfsfind
      
      - name: verify
        run: dist/ntfsfind.exe -h

      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ntfsfind.exe
