name: build-docker-image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: get version tag
        id: tag_number
        run: |
          CURRENT_TAG=$(git tag --sort=-creatordate | sed -n 1p)
          DOCKERHUB_TAG="${CURRENT_TAG//v/}"
          echo "::set-output name=dh_tag::${DOCKERHUB_TAG}"

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            sumeshi/ntfsfind:latest
            sumeshi/ntfsfind:${{steps.tag_number.outputs.dh_tag}}